[package]
name = "ia32_acpi_root"
version = "0.1.0"
edition = "2024"

[dependencies]
acpi = "5.2.0"
aml = "0.16.4"
executor = { version = "0.1.0", path = "../../file-server/executor" }
log = "0.4.27"
popcorn-server = { version = "0.1.0", path = "../../file-server/server" }
proto = { version = "0.1.0", path = "../proto" }
simple_logger = { version = "5.0.0", default-features = false }

[patch.crates-io]
fastrand = { path = "../../file-server/fastrand" }
